#!/usr/bin/env python3
"""
JELE Freshy แตงโม 2026 — Update Dashboard
Read JSON from scraper → inject into KOL_DATA in index.html
Usage: python3 scripts/update_dashboard.py scrape_results.json index.html
"""

import json
import sys
import re

# ============================================================
#  KOL METADATA — fallback data for all KOLs (generated by skill)
# ============================================================
KOL_METADATA = {
    "reviewmakro_fb": {
        "displayName": "รีวิวแมคโคร",
        "tier": "Page FB",
        "category": "Page FB",
        "gender": "-",
        "followers": 1000000,
        "budget": 54000
    },
    "yureefakel": {
        "displayName": "yureefakel",
        "tier": "Mom And Baby",
        "category": "Mom And Baby",
        "gender": "-",
        "followers": 82500,
        "budget": 8000
    },
    "pesoshekel": {
        "displayName": "pesoshekel",
        "tier": "Mom And Baby",
        "category": "Mom And Baby",
        "gender": "-",
        "followers": 23500,
        "budget": 9000
    },
    "flintfle": {
        "displayName": "flintfle",
        "tier": "Mom And Baby",
        "category": "Mom And Baby",
        "gender": "-",
        "followers": 13400,
        "budget": 8000
    },
    "fahfuufyyy": {
        "displayName": "fahfuufyyy",
        "tier": "สายชอบของน่ารัก/Note",
        "category": "สายชอบของน่ารัก/Note",
        "gender": "-",
        "followers": 12900,
        "budget": 7000
    },
    "allailovee": {
        "displayName": "allailovee",
        "tier": "สายชอบของน่ารัก/Note",
        "category": "สายชอบของน่ารัก/Note",
        "gender": "-",
        "followers": 17000,
        "budget": 7000
    },
    "dolinn__": {
        "displayName": "dolinn__",
        "tier": "สายชอบของน่ารัก/Note",
        "category": "สายชอบของน่ารัก/Note",
        "gender": "-",
        "followers": 21400,
        "budget": 9500
    },
}

KOL_LINKS = {
    "reviewmakro_fb": "https://www.facebook.com/share/17unLd8sow/",
    "yureefakel": "",
    "pesoshekel": "https://vt.tiktok.com/ZS9omNMYD/",
    "flintfle": "",
    "fahfuufyyy": "https://vt.tiktok.com/ZS9KXY8E8/",
    "allailovee": "https://vt.tiktok.com/ZSxJcsRFB/",
    "dolinn__": "https://vt.tiktok.com/ZSxJPDQDn/",
}

# KOLs ที่ยังไม่โพสต์ — ลบชื่อออกเมื่อโพสต์แล้ว
NOT_POSTED_KOLS = set(["reviewmakro_fb", "yureefakel", "flintfle"])

KOL_STATUS = {
    "reviewmakro_fb": "รอส่ง",
    "yureefakel": "Draft 2",
    "pesoshekel": "Posted",
    "flintfle": "Draft 1",
    "fahfuufyyy": "Posted",
    "allailovee": "Posted",
    "dolinn__": "Posted",
}




def preserve_actual_use(html_content):
    m = re.search(r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*([\d.]+)', html_content)
    return float(m.group(1)) if m else 0


def parse_existing_kol_data(html_content):
    """Parse existing KOL_DATA stats to preserve when scrape fails."""
    existing = {}
    pattern = r"\{\s*username:\s*'([^']+)'.*?followers:\s*(\d+).*?views:\s*(\d+).*?likes:\s*(\d+).*?shares:\s*(\d+).*?comments:\s*(\d+).*?saves:\s*(\d+)"
    for m in re.finditer(pattern, html_content):
        username = m.group(1)
        existing[username] = {
            'followers': int(m.group(2)),
            'views': int(m.group(3)),
            'likes': int(m.group(4)),
            'shares': int(m.group(5)),
            'comments': int(m.group(6)),
            'saves': int(m.group(7)),
        }
    return existing


def js_escape(s):
    if s is None:
        return ''
    return str(s).replace('\\', '\\\\').replace("'", "\\'")


def build_kol_entry(username, scrape_data, link='', existing_data=None):
    meta = KOL_METADATA.get(username, {})
    sd = scrape_data.get(username, {})
    ex = (existing_data or {}).get(username, {})

    display_name = meta.get('displayName', username)
    tier = meta.get('tier', 'Unknown')
    category = meta.get('category', 'Unknown')
    gender = meta.get('gender', '-')
    followers = sd.get('followers', 0) or meta.get('followers', 0)
    budget = meta.get('budget', 0)

    if username in scrape_data:
        views = sd.get('views', 0)
        likes = sd.get('likes', 0)
        shares = sd.get('shares', 0)
        comments = sd.get('comments', 0)
        saves = sd.get('saves', 0)
    else:
        views = ex.get('views', 0)
        likes = ex.get('likes', 0)
        shares = ex.get('shares', 0)
        comments = ex.get('comments', 0)
        saves = ex.get('saves', 0)

    posted = username not in NOT_POSTED_KOLS and bool(link)
    posts = 1 if posted else 0
    kpi_views = views

    status = KOL_STATUS.get(username, 'รอส่ง')
    return (
        f"  {{ username: '{js_escape(username)}', displayName: '{js_escape(display_name)}', "
        f"tier: '{js_escape(tier)}', platform: 'TikTok', category: '{js_escape(category)}', "
        f"gender: '{js_escape(gender)}', followers: {followers}, "
        f"views: {views}, likes: {likes}, shares: {shares}, "
        f"comments: {comments}, saves: {saves}, "
        f"posts: {posts}, kpi_views: {kpi_views}, "
        f"posted: {'true' if posted else 'false'}, "
        f"link: '{js_escape(link)}', budget: {budget}, "
        f"status: '{js_escape(status)}' }}"
    )


def main():
    if len(sys.argv) < 3:
        print("Usage: python3 scripts/update_dashboard.py scrape_results.json index.html")
        sys.exit(1)

    json_file = sys.argv[1]
    html_file = sys.argv[2]

    try:
        with open(json_file, 'r') as f:
            scrape_data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        scrape_data = {}

    with open(html_file, 'r', encoding='utf-8') as f:
        html = f.read()

    actual_use = preserve_actual_use(html)
    existing_data = parse_existing_kol_data(html)

    entries = []
    for username in KOL_METADATA.keys():
        link = KOL_LINKS.get(username, '')
        entry = build_kol_entry(username, scrape_data, link, existing_data)
        entries.append(entry)

    new_kol_data = "const KOL_DATA = [\n" + ",\n".join(entries) + "\n];"

    pattern = r'const\s+KOL_DATA\s*=\s*\[[\s\S]*?\];'
    html = re.sub(pattern, new_kol_data, html, count=1)

    html = re.sub(
        r'const\s+CAMPAIGN_ACTUAL_USE_DEFAULT\s*=\s*[\d.]+',
        f'const CAMPAIGN_ACTUAL_USE_DEFAULT = {actual_use}',
        html
    )

    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"Dashboard updated: {html_file}")
    print(f"KOLs updated: {len(entries)}")
    print(f"Scraped data injected: {len(scrape_data)} KOL(s)")
    print(f"Actual Use preserved: {actual_use:,.0f}")


if __name__ == '__main__':
    main()
